version: '3'

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: mallzz
      POSTGRES_PASSWORD: mallzz52
      POSTGRES_DB: carrentaldb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5434:5432"

  adminer:
    image: adminer
    ports:
      - "8085:8080"

  web:
    build:
      context: .
      dockerfile: Dockerfile.txt
    environment:
      FLASK_ENV: development
    ports:
      - "5000:5000"
    depends_on:
      - db
    volumes:
      - .:/app
    command: flask run --host=0.0.0.0

volumes:
  postgres_data:
